version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./backend/db:/backend/db
    ports:
      - 27017:27017
    restart:
      "always"
    command: mongod --bind_ip_all

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 1337:1337
    restart:
      "always"
    command: "npm run dev"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    restart:
      "always"
    command: "npm start"
