

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
        
    - name: Install backend dependencies
      run: (cd ./backend && exec npm install)
      
    - name: Run backend tests
      run: (cd ./backend && exec npm run test:actions)

    - name: Install frontend dependencies
      run: (cd ./frontend && exec npm install)
      
    - name: Run frontend tests
      run: (cd ./frontend && CI=true exec npm run test:actions)
      env:
        REACT_APP_API_URL_DEV: ${{ secrets.REACT_APP_API_URL_DEV }}
        REACT_APP_API_URL_PROD: ${{ secrets.REACT_APP_API_URL_PROD }}

